name: Run CO2 Forecast Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # No folder path needed
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the forecast script
        # Use the correct filename with the typo
        run: python forecast_co2.py.py

      - name: Commit and push updated plot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # No folder path needed
          git add forecast_plot.png
          git diff --quiet && git diff --staged --quiet || git commit -m "Update forecast plot automatically"
          git push
