name: Run CO2 Forecast Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # We specify the path to requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r Econometric-CO2-Forecasting-for-India-SARIMAX/requirements.txt

      - name: Run the forecast script
        # We specify the path to the python script
        run: python Econometric-CO2-Forecasting-for-India-SARIMAX/forecast_co2.py

      - name: Commit and push updated plot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # We specify the path to the plot file to be added
          git add Econometric-CO2-Forecasting-for-India-SARIMAX/forecast_plot.png
          git diff --quiet && git diff --staged --quiet || git commit -m "Update forecast plot automatically"
          git push
